### ISSUE TITLE
Missing slash between domain and rest of the URL

### ISSUE THREAD

**Issue by oparoz** [kanboard/plugin-github-webhook#3]
Under `/project/xx/integrations`, there is a "Github webhooks" entry and the URL is:

`domain.comwebhook/github...`

It should be 

`domain.com/webhook/github...`

Not sure if it's a general problem which should be fixed in kanboard itself or a problem with plugins.

**Comment by fguillot** [comment]
Can you check if the url specified in application settings contains a slash at the end?

**Comment by oparoz** [comment]
It doesn't, but `KANBOARD_URL` in config.php does.

Maybe I should open a feature request in `kanboard` to make sure the script always adds the slash in case it's missing?

**Comment by fguillot** [comment]
- `KANBOARD_URL` is not used anymore, only the config option in application settings is used (I will update the inline help).
- Saving the form in application settings will automatically add the missing slash at the end (just submit the form).

**Comment by oparoz** [comment]
Sounds good :+1:. Thank you.
