### ISSUE TITLE
Assigned user is not imported

### ISSUE THREAD

**Issue by kamov** [kanboard/plugin-github-webhook#4]
Hi

Create a task from github don't assign to user.
The user have the same username and also is connected with github.

This is setting:
    Event name = Github issue opened
    Action name = Create a task from an external provider

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
