### ISSUE TITLE
documentation required for installation

### ISSUE THREAD

**Issue by rbuckland** [kanboard/plugin-github-webhook#5]
Hi,

The documentation states to use a Webhook URL found under  `Settings > Integrations`

> Payload url: Copy and paste the link from the Kanboard project settings (section Integrations > Github).

But there is no "Github" URL there.

The Github Auth is working and both plugins are installed.

```
Installed Plugins
Name    Author  Version Action
Github Authentication   Frédéric Guillot  1.0.2    Uninstall
Use Github as authentication provider
Github Webhook  Frédéric Guillot  1.0.3    Uninstall
Bind Github webhook events to Kanboard automatic actions
```

I derived a URL by looking at the code that the webhook URL is possibly .. 

```
http://kanboard.host/webhook/github/
```

But that seems to get redirected (302) .. to /login

```
Cache-Control: no-store, no-cache, must-revalidate
Connection: keep-alive
Content-Length: 0
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src * data:;
Content-Type: text/html; charset=UTF-8
Date: Wed, 14 Sep 2016 14:52:18 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Location: /login
Pragma: no-cache
Server: nginx
Set-Cookie: KB_SID=lSbb60wE-mVAIQvrhyHGsn%2C5LA4; path=/; HttpOnly
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Comment by rbuckland** [comment]
any suggestions would be great

**Comment by igordavid** [comment]
+1

Is the Webhook URL this one maybe?

https://kanboard.host/plugins/GithubWebhook

Thanks in advance.

**Comment by fguillot** [comment]
Sorry to answer so late, but the webhook URL is visible in the project settings, not in the application settings.

![project-github-webhook](https://cloud.githubusercontent.com/assets/323546/20451514/394fca12-adc8-11e6-8689-12dfae9e29f6.png)

I updated the documentation to avoid the confusion.

Thanks.
