### ISSUE TITLE
Two-way integration with Github

### ISSUE THREAD

**Issue by brylie** [kanboard/plugin-github-webhook#9]
Github webhooks module seems to be one-way, meaning Github only pushes events to Kanboard. Is it planned, or currently possible, for Kanboard to push events back to Github?

E.g. when commenting on a Kanboard card, the comment would appear on the Github issue. We are practicing an open development methodology and would like to keep our kanboard issues open and synchronized.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
